#
# As of 2022-02-25 we use GitHub Actions to run CI.
# See the `.github` directory.
#

language: node_js
node_js:
  - "16"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
before_script:
  - export CTF_SPACE_ID='1'; export CTF_CDA_ACCESS_TOKEN='1';
script:
  - yarn run unit
