#!/usr/bin/with-contenv sh

cd $NODE_APP_DIR

# generates the config file if not already present
CONFIG_FILE=.contentful.json
[ -f ${CONFIG_FILE} ] || envsubst < ${CONFIG_FILE}.tmpl > ${CONFIG_FILE}

# generate the client static files
[ -f ${CONFIG_FILE} ] || node_modules/nuxt/bin/nuxt-generate

# the deps install and the build occured in the Dockerfile
echo "==> Starting the server"
exec npm start -- -H 0.0.0.0
