#!/usr/bin/with-contenv sh

cd $NODE_APP_DIR

# build the site if .nuxt folder is not present
[ -d .nuxt ] || yarn run build

# the deps install and the build occured in the Dockerfile
echo "==> Starting the server"
export NUXT_HOST=0.0.0.0
exec ./node_modules/pm2/bin/pm2 start npm --name "dsr-nuxt" --no-daemon -- start
