#!/usr/bin/with-contenv sh

cd $NODE_APP_DIR

# run it if .nust folder is not present
[ -d .nuxt ] || yarn run build

# the deps install and the build occured in the Dockerfile
echo "==> Starting the server"
exec npm start -- -H 0.0.0.0
